version: "3.8"
services:
  mongodb:
    container_name: database
    image: mongo
    expose:
      - "27017"
    ports: 
      - "27017:27017"
    volumes:
      - api:/data/db

  backend:
    build: ./server
    tty: true
    ports:
      - "3001:3001"
    volumes:
      - ./server:/server
    depends_on:
      - mongodb
  frontend: 
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  api: